### ISSUE TITLE
Icon for private network websites

### ISSUE THREAD

**Issue by zivkr2** [eladnava/applicationize#1]
Applicationize is unable to fetch the favicon from private network websites that require VPN for accesses.

The  suggested solution is to create a generic icon from the first letter of the domain name,
like the default icon in the gmail app, a simple colored circle with the First letter centered inside.

use this icon for hxxps://fakeinternalsite.com for example
![image](https://cloud.githubusercontent.com/assets/10366852/12166212/f2609a12-b52c-11e5-9808-e3b976026392.png)

**Comment by eladnava** [comment]
@zivkr2 Excellent idea! 

I was able to create a generic icon with a white, thin Roboto letter using the following SVG:

```html
<svg width="512" height="512">
  <circle cx="230" cy="230" r="230" fill="#E91E63" />
  <text x="230" y="235" alignment-baseline="central" text-anchor="middle" fill="#fff" font-size="275" font-weight="100" font-family="Roboto">X</text>
</svg>
```

This is how it looks:

![screen shot 2016-01-14 at 5 00 14 pm](https://cloud.githubusercontent.com/assets/4394189/12327697/9ec191cc-bae0-11e5-8eeb-a104c4c8e5a7.png)

What do you think? If you like the way it looks, we'll need to generate an SVG for each letter and number (A-Z, 0-9) and improve the `crx` generator code to use these images if the webapp URL fails to load for some reason.

**Comment by eladnava** [comment]
@zivkr2 I created a Material letter icons generator in Node.js:
https://github.com/eladnava/material-letter-icons

![screen shot 2016-01-15 at 3 55 02 pm](https://cloud.githubusercontent.com/assets/4394189/12354713/5dfd0d86-bba0-11e5-827f-2f78fb76491a.png)

Now all that's left is to integrate the generated icons into applicationize. =)

**Comment by eladnava** [comment]
@zivkr2 It has been implemented. We now support unreachable URLs! Give it a shot at http://applicationize.com/.
