### ISSUE TITLE
Make it possible to upload a custom shortcut icon

### ISSUE THREAD

**Issue by eladnava** [eladnava/applicationize#10]
Louis Guthmann suggested making it possible to upload a custom shortcut icon, instead of the web app's declared `<link>` shortcut icon / fallback letter icon.

This is a great idea, and it can be easily implemented once the new redesigned website is up -- it contains an improved layout that will make it more natural to display these customizations.

**Comment by kyprifog** [comment]
+1

**Comment by eladnava** [comment]
The website redesign is complete, just need to find some time to implement an (optional) icon upload form.

**Comment by eladnava** [comment]
Hi @kyprifog,
As per your request, I found some free time and the feature has finally been implemented!

Check it out:
https://applicationize.me/now

---

![screen shot 2016-04-21 at 6 59 10 pm](https://cloud.githubusercontent.com/assets/4394189/14715854/27c84178-07f3-11e6-94a1-5a2fb22674f9.png)

**Comment by kyprifog** [comment]
Awesome thanks!
