### ISSUE TITLE
Is there a way to enable --kiosk-printing?

### ISSUE THREAD

**Issue by Double5peed** [eladnava/applicationize#101]
Is there a way to enable **--kiosk-printing** in order to skip the printer dialogue?

**Comment by eladnava** [comment]
Hi @Double5peed,
Sure, please consider this solution:

1) Unpack crx generated by Applicationize:
```
unzip ~/Downloads/www.messenger.com.crx -d ~/Downloads/applicationize
```

2) Follow these instructions to add the following JSON parameters to the `manifest.json` file:

```
"kiosk_enabled": true,
"kiosk_only": true
```

More info:
https://stackoverflow.com/a/32441567/1123355

3) Load unpacked extension from `chrome://extensions` page by pointing to the relevant folder.

As this is quite an unpopular request, it will not be getting baked into Applicationize for now.

**Comment by Double5peed** [comment]
Thanks for getting back to me, I've tried this however doesn't seem to work I get an error with the flag kiosk_only it says...

'kiosk_only' is not allowed for specified platform.

and including the kiosk_enabled doesn't hide the printer dialogue, do you have any other ideas?

**Comment by eladnava** [comment]
@Double5peed Well, the docs for `Kiosk Apps` don't really cover anything about removing the print dialog:
https://developer.chrome.com/apps/manifest/kiosk_enabled

Maybe it's just not supported within Chrome Packaged Apps.
