### ISSUE TITLE
Print doesn't work

### ISSUE THREAD

**Issue by mpadmaraj** [eladnava/applicationize#104]
Is there a way to enable "Ctrl +P" or allow javascript to print from within the extension?

**Comment by eladnava** [comment]
Hi @mpadmaraj,
I've added this in https://github.com/eladnava/applicationize/commit/c68e44d591ff3ad36f35d28f101308a59d347ccd and deployed to production. Please re-generate your Applicationize extensions and print using `Ctrl / CMD + P`. 👍

**Comment by mpadmaraj** [comment]
awesome!!! that was quick! thank you 👍

**Comment by eladnava** [comment]
🤙
