### ISSUE TITLE
URLs not associated to app; links clicked in browser still open in browser

### ISSUE THREAD

**Issue by mblais** [eladnava/applicationize#105]
Is there any way to make all "https://myapp.app/xyz" links open in the generated app when clicked in Chrome browser? Right now they open in a Chrome tab just like they used to.

**Comment by eladnava** [comment]
Hi @mblais,
Please tick the `Would you like app links to open internally as popups?` option in `(advanced options)` when generating your Applicationize app:
https://applicationize.me/now

![Screen Shot 2020-02-01 at 10 14 37 AM](https://user-images.githubusercontent.com/4394189/73574864-abdaef00-44db-11ea-9bb8-1755833a7b81.png)

**Comment by mblais** [comment]
Does this only work for links clicked inside the app itself? I'm trying to get **any** related app links to open **in the app**, even if they are clicked in a Chrome tab. Is that possible? App links clicked in a Chrome tab still open in Chrome.

**Comment by eladnava** [comment]
Hi @mblais,
Unfortunately that's not really possible with Applicationize.

It might be possible if you went and developed a Chrome Extension to somehow focus the Applicationize Packaged App when one of those links is clicked. But at this time, this is not something Applicationize supports out of the box.
