### ISSUE TITLE
Allow changing of version number and description.

### ISSUE THREAD

**Issue by dolfies** [eladnava/applicationize#108]
I really love your site, but often find myself to have to repack it because seeing a generic description in the extensions page is not ideal.

**Comment by eladnava** [comment]
Hi @dolfies,
Thanks for the feedback.

I'm not really sure what improvement customizing the description or version number brings to the project as it's only a textual string displayed in the `chrome://extensions` page. If you have a desire to change it, that's fine, but I feel like most users are not bothered by it.

Closing for now.
