### ISSUE TITLE
CRX required

### ISSUE THREAD

**Issue by marandaneto** [eladnava/applicationize#109]
Hey, I've generated the extension, downloaded it and tried to install it, that's what I've got, thanks.

<img width="437" alt="Screenshot 2020-05-06 at 09 17 07" src="https://user-images.githubusercontent.com/5731772/81147428-919d2b00-8f7a-11ea-8958-3847101b8c57.png">

**Comment by eladnava** [comment]
Duplicate: #https://github.com/eladnava/applicationize/issues/99#issuecomment-601468565.

**Comment by marandaneto** [comment]
my bad, thx
