### ISSUE TITLE
Allow for shortcut / right-click freedom in apps

### ISSUE THREAD

**Issue by fredericosantos** [eladnava/applicationize#113]
When using Applicationize, the website becomes rather strict to what we can do, we can't inspect it, we can't use Chrome OS shortcuts (refresh button does not work, only Ctrl + R);

Is it possible, on the webpage, to have more freedom to select what we want or not want? For example, Ctrl + F uses the app Search and does not let the Web App Search shortcut to happen (for Jupyter lab for example).

**Comment by eladnava** [comment]
Hi @fredericosantos,
Thanks for your suggestions. 

While it's possible to support the requested functionality within Applicationize, it would take some effort. In the meantime, I would recommend simply using a built in feature baked into Chrome which should support these features.

There is a new feature in Google Chrome called Application Shortcuts. It basically makes it possible to convert any web page (or web app) into a desktop app by clicking the hamburger icon in the top right -> More Tools -> Create Shortcut and ticking "Open as window". Please give it a try and let me know if it supports these features.
