### ISSUE TITLE
OpenSSL Issue

### ISSUE THREAD

**Issue by ddlidded** [eladnava/applicationize#115]
{"error":"Could not find openssl on your system on this path: openssl"}

when running locally!

**Comment by eladnava** [comment]
Hi @ddlidded,
This can occur when trying to run on a Windows machine without `openssl` which is required by the `pem` package.

1) Download and unpack `openssl` from here: http://downloads.sourceforge.net/gnuwin32/openssl-0.9.8h-1-bin.zip
2) Add `bin/openssl.exe` to the system's `PATH`: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/
3) Open a command prompt and type `openssl`. It should display:

```
OpenSSL> 
```
