### ISSUE TITLE
app dont show notifications

### ISSUE THREAD

**Issue by cgman7** [eladnava/applicationize#116]

**Comment by eladnava** [comment]
Hi @cgman7,
Please enable `Would you like applications to be able to send you notifications?` under `(advanced options)` when generating the extension:
https://applicationize.me/now

**Comment by cgman7** [comment]
How do you think that i find applicationize and dont know what function it has in advance menu while generating the extention?
its on for sure. i turn on every function it has.
[https://i.imgur.com/EgJpL12.jpg](url)

**Comment by eladnava** [comment]
Hi @cgman7,
Excellent, thanks for confirming you have enabled it in `(advanced options)`. 

By notifications, are you expecting these web apps to be able to send you Web Push notifications, or local Desktop Notifications? The former (Web Push) can work while the web app window is closed, whereas the latter (Desktop Notifications) only work while the web app is open.

Currently, Applicationize only supports the latter (Desktop Notifications). Please confirm you are trying to receive Desktop Notifications.

If this is the case, try to first visit the website in Chrome (not within Applicationize), and consent to receiving notifications when asked to do so, and then try to receive them in Applicationize.

**Comment by cgman7** [comment]
Hi,
my app is nextcloud. so, that could be my app issue!
because it's sometimes not showing the notification in the browser too!
there are lots of discussions about nextcloud notification.
BTW, if you know anything about resolving or improving nextcloud
notification please let me know :) or enabling push notification for
nextcloud.
Thank you very much!!
