### ISSUE TITLE
Links within Applicationize window don't open in new browser - about:blank#blocked URL opens instead

### ISSUE THREAD

**Issue by noahfreedman** [eladnava/applicationize#117]
When I click an external link in Applicationize window (I'm clicking a Zoom link from Google Calendar), a tab opens in my main Chrome browser with the URL about:blank#blocked, and nothing loaded.

Is it possible to have the actual link open in the new tab in the main Chrome browser instead of a blank error page?

I tried this with the Open Internally as Pop-ups option both on and off, and still get the same response.

**Comment by eladnava** [comment]
Duplicate issue #36. Possible workaround:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260
