### ISSUE TITLE
Chrome OS Zoom Level Reset

### ISSUE THREAD

**Issue by Mr-Jree** [eladnava/applicationize#119]
I often find that some apps reset their zoom level and some can't even zoom in and out.

For example, Gmail made from applicationize.me/now has their zoom level reset on computer sleep I think, and Asana.com can't zoom in and out but if opened in a chrome browser they can.

Is this intended?

**Comment by eladnava** [comment]
Hi @Mr-Jree,
How are you zooming in? I can't reproduce the zoom level reset on sleep. It's even remember for when I close and re-open the Applicationized Gmail app.

As per Asana.com, I tried it but only on the home page (as I don't have an Asana account) so I can't test the dashboard zoom functionality, but it works on their landing page.

If you can provide any URL which I can Applicationize to reproduce this bug, please let me know.

**Comment by Mr-Jree** [comment]
Hi @eladnava , I am zooming in with CTRL + (+ or -), and I am on Chrome OS.

For asana, the URL is app.asana.com/0/#/board. It is the board level view.

And as for GMail, I am not sure how to reproduce it, all I notice sometimes the zoom level is reset upon waking up my Pixelbook Go!

**Comment by eladnava** [comment]
HI @Mr-Jree,
Indeed, I can reproduce the issue with zoom controls not working for Asana!

It happened because Asana is setting a `window.onkeydown` listener and it overrides Applicationize's. 

Commit https://github.com/eladnava/applicationize/commit/ca52f84ee58dc21855ac7033bf553795d7c488a7 fixes that. Please re-generate and re-install the extension from this page and try again: 
https://applicationize.me/now

Thanks for your report!

**Comment by Mr-Jree** [comment]
Hi Elad,

I just tried it and it still doesn't work.
Best,
Jerry

**Comment by eladnava** [comment]
Hi Jerry,
It appears it works only after you login to Asana, then quit and re-launch the Asana Applicationize app. Can you reproduce?

**Comment by Mr-Jree** [comment]
Yes this worked after closing. I tried the same with upvoty.com/admin and that doesn't work.

**Comment by eladnava** [comment]
@Mr-Jree It appears I might need a username and password into that dashboard to test.
