### ISSUE TITLE
about:blank#blocked Clicking Links from App

### ISSUE THREAD

**Issue by Mr-Jree** [eladnava/applicationize#122]
I made a Google Calendar app with Applicationize and when I click on meeting links to join meetings, I get about:blank#blocked in the Chrome window. FWIW it is a Zoom link.

I have the open pop up internally checked when making the Google Calendar app, not sure if that's why this is happening. But basically I cannot click on any links in the Google Calendar app I made w/ Applicationize.

**Comment by eladnava** [comment]
Hey @Mr-Jree. Duplicate issue #36. Possible workaround:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260

**Comment by Mr-Jree** [comment]
That shortcut doesn't work well for Google webpages because if I were to create a shortcut on https://calendar.google.com/calendar/u/1/r, opening the shortcut takes me to https://calendar.google.com/calendar/u/0/r, which is the wrong user's calendar since I have multiple users logged in (one personal and one work, the number denotes the order of the account). The only reason I started using Applicationize is to bypass that stupid Google shortcut design. The same goes with Mail, and Drive. Creating a shortcut on a work account will open it in a personal account and not the work account.

**Comment by eladnava** [comment]
@Mr-Jree A cool hack is to "Create Shortcut" on the following URL:
```
https://accounts.google.com/AccountChooser/signinchooser?continue=https%3A%2F%2Fcalendar.google.com&service=mail&Email=USERNAME%40DOMAIN&flowName=GlifWebSignIn&flowEntry=AccountChooser
```

This will allow you to select the account you wish to view the calendar for (when opening the app).

**Comment by Mr-Jree** [comment]
How do you "Create Shortcut" on the URL? Once I use the URL and change the email, it takes me to https://calendar.google.com/calendar/u/1/r again.

**Comment by eladnava** [comment]
@Mr-Jree Don't select an e-mail yet. Simply create a shortcut (More Tools -> Create Shortcut) after visiting the URL:
```
https://accounts.google.com/AccountChooser/signinchooser?continue=https%3A%2F%2Fcalendar.google.com&service=mail&Email=USERNAME%40DOMAIN&flowName=GlifWebSignIn&flowEntry=AccountChooser
```
