### ISSUE TITLE
Trouble with downloading

### ISSUE THREAD

**Issue by yarnell902** [eladnava/applicationize#123]
Hi there,

I have converted your site (https://applicationize.me/now) to an app and I have to say, I love the look and feel of how a website is presented. I did however, run into a minor issue. When I try to run applicationize.me from within the new app it does not work. I do not get the save dialog box as per usual.

Not sure if you were aware of that or not so I figured I'd let you know.

Thanks.

**Comment by eladnava** [comment]
Hi @yarnell902,
Thanks for your kind words. However, can I ask why you would want to Applicationize Applicationize itself?

**Comment by yarnell902** [comment]
I added applicationize to my start menu for quick access. After playing around with a few different site I notice that downloading was an issue so I tried doing the applicationize website and it still didnt work.

After playing around a little more I notice that the downloads will start if I have another chrome window open.

**Comment by eladnava** [comment]
@yarnell902 Nice catch. This is indeed a limitation of Google Chrome. The UI for managing downloads is only implemented in a real Chrome browser window, therefore, one must be open for you to download things. This is acceptable behavior.
