### ISSUE TITLE
Make other extensions work within applications

### ISSUE THREAD

**Issue by saltedcoffii** [eladnava/applicationize#124]
Is there a way to make extensions work within these applications?

For example, I'd like to be able to run things like an ad blocker or Dark Reader within the application.

Thank you!

**Comment by eladnava** [comment]
Hi @saltedcoffii,
Please see duplicate issue here: https://github.com/eladnava/applicationize/issues/21#issuecomment-239841116, and the workaround mentioned here which allows using extensions:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260
