### ISSUE TITLE
App Notification Not Triggering

### ISSUE THREAD

**Issue by Mr-Jree** [eladnava/applicationize#125]
I just made a Slack app with Applicationize, and I am unable to click the "Allow desktop notification" link in the app itself to set up desktop notifications for the app.

**Comment by eladnava** [comment]
Hi @Mr-Jree,
Please re-generate the extension in https://applicationize.me/now, enabling the following setting:
**Would you like applications to be able to send you notifications?**

It is listed under **(advanced options)**. 

Then, try again. 👍

**Comment by Mr-Jree** [comment]
The option was checked when I created the app, it did not work.

**Comment by eladnava** [comment]
Hi @Mr-Jree,
I believe that even if no dialog is displayed to allow/deny notifications, when you click to allow notifications in Slack, it will automatically consent and you should start receiving desktop notifications.

**Comment by Mr-Jree** [comment]
It does not, I have tried.

This is why I am led to believe you HAVE to click the dialog to have the chrome "Allow desktop notifications from this app?" to pop up in order to start receiving desktop notifications.

**Comment by eladnava** [comment]
Hi @Mr-Jree,
I'm unable to reproduce. It works for me: 

![Screen Shot 2021-04-28 at 10 12 43 AM](https://user-images.githubusercontent.com/4394189/116436913-19beb500-a80a-11eb-8483-6abc67e3c007.png)

Here's the steps I took to confirm notifications are working:

1. Applicationize the URL `https://app.slack.com/` (enabled notifications under Advanced Options).
2. Log into Slack & go to Preferences -> Notifications.
4. Under "Sound & appearance", I clicked "Show an example":

![Screen Shot 2021-04-28 at 10 13 59 AM](https://user-images.githubusercontent.com/4394189/116437044-3f4bbe80-a80a-11eb-80ce-d5f8ba54e5a5.png)

5. The notification was displayed.

Please give it a try to confirm it works for you.
