### ISSUE TITLE
Allow chrome URLs to be used

### ISSUE THREAD

**Issue by leonbollerup** [eladnava/applicationize#126]
Hi,

I would like to create and application from a chrome extention URL - currently i have a notes application that resides as an extention icon in chrome - i grapped the full URL and run it as a shortcut in fullscreen which works great - but logically the icon is extremely ugly.

I tried to use the webpage to create and application - but that dident work - i got an error that the url needs to contain https.

My ext. url is: chrome-extension://ndidogegapfaolpcebadjknkdlladffa/src/app/popup.html

**Comment by eladnava** [comment]
Hi @leonbollerup,
Unfortunately creating an Applicationized version of Chrome packaged extensions / apps isn't supported at this time.

If all you're trying to change is the icon, that's pretty easy to do by opening the following directory:
```
/Users/**/Applications/Chrome Apps.localized/
```
There, you will find the Chrome app, where you can override its icon (on OS X) by right clicking -> **Get Info** and dragging and dropping a new icon onto the icon showed in the info window. Here's a guide:
https://9to5mac.com/2020/12/01/change-mac-icons/
