### ISSUE TITLE
Back et Refresh buttons on Chrome Apps

### ISSUE THREAD

**Issue by NomUtilisateur** [eladnava/applicationize#128]
Hello ,

Is there something to add the back button and refresh button on Applicationize app ? 

Like that : 
https://ibb.co/gJLW2xB

In Top left corner 

Thanks

**Comment by NomUtilisateur** [comment]
I already saw for Keyboard shortcut but not really practical

**Comment by eladnava** [comment]
Hi @NomUtilisateur,
Currently, Applicationize does not have any kind of UI bar except for the page itself being applicationized. 

I would recommend simply using a built in feature baked into Chrome which contains back button / refresh functionality.

There is a new feature in Google Chrome called Application Shortcuts. It basically makes it possible to convert any web page (or web app) into a desktop app by clicking the hamburger icon in the top right -> More Tools -> Create Shortcut and ticking "Open as window". Please give it a try and let me know if indeed it supports these features (it does when I test it).
