### ISSUE TITLE
Possible to add Chrome DevTools

### ISSUE THREAD

**Issue by dolfies** [eladnava/applicationize#129]
Hello, is there a possibility of allowing the use of the Chrome DevTools? Currently `CTRL + SHIFT + I` does nothing.

EDIT: I've been doing some research, and I might open a pull request later if I find a way.

**Comment by eladnava** [comment]
Hi @dolfies,
This is a great suggestion. Unfortunately, it does not appear to be possible for a Chrome extension to open the Developer Tools at this time, according to multiple sources:
https://groups.google.com/g/google-chrome-developer-tools/c/1mVms-x_31k?pli=1
https://stackoverflow.com/questions/6801577/can-i-programmatically-open-the-devtools-from-a-google-chrome-extension

I would recommend simply using a built in feature baked into Chrome which supports this functionality.

There is a new feature in Google Chrome called Application Shortcuts. It basically makes it possible to convert any web page (or web app) into a desktop app by clicking the hamburger icon in the top right -> More Tools -> Create Shortcut and ticking "Open as window". Please give it a try and let me know if indeed it resolves your issue.
