### ISSUE TITLE
make a shell tool

### ISSUE THREAD

**Issue by yinrong** [eladnava/applicationize#132]
all website I access have SSO auth. could you make a shell tool, let me input icon path, title ?

**Comment by eladnava** [comment]
Hi @yinrong,
Thanks for your inquiry.

The shell tool you are looking for is [nativefier](https://github.com/nativefier/nativefier), and the respective parameters are [--icon](https://github.com/nativefier/nativefier/blob/master/API.md#icon) and [--name](https://github.com/nativefier/nativefier/blob/master/API.md#name).
