### ISSUE TITLE
"applicationize.me/now refused to connect" on ChromeOS

### ISSUE THREAD

**Issue by Grap8** [eladnava/applicationize#138]
Hi. I wanted to use the website to create a web app on my Chromebook shelf. I went to the website and it said, "applicationize.me/now refused to connect". Has the website been shut down? Is there an updated website? What happened?

**Comment by eladnava** [comment]
Hi @Grap8,
Thanks for letting me know. It was a temporary server issue. It's up again and being monitored for uptime. 🎉

**Comment by Grap8** [comment]
Thanks for fixing it! Now I can use it
