### ISSUE TITLE
error: Invalid protocol: data | https://www.xbox.com/play

### ISSUE THREAD

**Issue by PhantomNimbi** [eladnava/applicationize#140]
I have attempted to make an app with this for XBox Cloud Gaming which uses the web addresse: https://www.xbox.com/play and it always errors out. The page it displays simply shows this : 

```json
{"error":"Invalid protocol: data:"}
```
I'm not sure if this would count as a lack of support for such since it worked flawlessly when I made an app for the service itself using https://applicationize.me/now as the website url. So all I can think of is that something is causing the script to fail?

If you can look into this and maybe see if it can be fixed, I would be more than grateful.

**Comment by eladnava** [comment]
Hi @PhantomNimbi,
It appears Applicationize is failing because that URL redirects to `https://www.xbox.com/en-US/play`.

Please try generating an extension using the following URL, it will work:
```
https://www.xbox.com/en-US/play
```
