### ISSUE TITLE
Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'

### ISSUE THREAD

**Issue by longshadowdev** [eladnava/applicationize#142]
Hello, this website worked for me a few weeks okay but no longer works.

In Chrome 103.0.5060.134 (Official Build) (arm64) on Mac OSX.

Chrome seems to attempt to download the generated package, try to immediately install it, throw the error in the title, and then 'clean up' (delete) the downloaded package, so that it can't be installed manually.

I looked in the Bin (mac recycle bin) and they are not there either.

Using Safari worked, and I was able to install the extension created using Safari into Chrome, and from there it worked as per normal.

**Comment by eladnava** [comment]
Hi @longshadowdev,
Please try the solution posted here:
https://github.com/eladnava/applicationize/issues/92#issuecomment-508728404
