### ISSUE TITLE
Ok. It is cool and all but its not working

### ISSUE THREAD

**Issue by RockyYT1** [eladnava/applicationize#146]
I tryed using this on chromeOS extensions are used but nothing happens
i get a error message 
![Screenshot 2022-11-29 4 19 56 PM](https://user-images.githubusercontent.com/86290259/204650384-081be1f7-7975-4f5b-bcaa-0d4c76450019.png)
![Screenshot 2022-11-29 4 21 19 PM](https://user-images.githubusercontent.com/86290259/204650456-4f491589-32d5-48c3-bab1-cfc0cde46877.png)

**Comment by eladnava** [comment]
Hi @RockyYT1,
Please try the solution posted here:
https://github.com/eladnava/applicationize/issues/92#issuecomment-508728404

**Comment by RockyYT1** [comment]
Thank you very much eladnava now my chromebook look like windows 95 
![Screenshot 2022-12-01 12 51 35 PM](https://user-images.githubusercontent.com/86290259/205125055-ae2b8f24-65bd-4754-913d-0eadf1483bb6.png)
