### ISSUE TITLE
"Chrome Apps will no longer be launchable on Windows, Mac, and Linux"

### ISSUE THREAD

**Issue by rdmdk** [eladnava/applicationize#148]
https://support.google.com/chrome/thread/174381169?visit_id=638094580633455921-3194347272&p=chrome_app_deprecation&rd=1

Well that's a shame

Applicationize has been really useful over the years

**Comment by eladnava** [comment]
Hi @rdmdk,
Unfortunately, that appears to be the case. Chrome has always hinted at removing support for Packaged Apps and Hosted Apps.

We have yet to see whether loading Packaged Apps via `.crx` file will still work (or if this will only affect the Chrome Web Store apps). If not, then unfortunately, this project will become deprecated, and the alternative is already built-into Chrome.

Google Chrome comes with a built-in feature called Application Shortcuts. It basically makes it possible to convert any web page (or web app) into a desktop app by clicking the hamburger icon in the top right -> More Tools -> "Create Shortcut" and ticking "Open as window".

Give it a try, and let me know if it works for you.

**Comment by rdmdk** [comment]
@eladnava 

Only raised this because yesterday I had started getting notifications whenever I opened the app that Chrome/Chromium no longer supported it. Though I am still able to access it but only after acknowledging it's no longer supported which can get annoying rather quickly.

Their support docs recommended converting it to a PWA so I added a service worker to one of my lightweight webapps but that adds a translucent toolbar to the top of the app (not ideal), similar to what gets added when creating a shortcut via More Tools as you suggested.

Presently looking at alternative webapp to nativeapp solutions though they're not quite as convenient as Applicationize :)

**Comment by eladnava** [comment]
@rdmdk Have you tried the built-in "Create Shortcut" functionality in my reply above? 

Why didn't that fit that bill?

You can also take a look at [nativefier](https://github.com/nativefier/nativefier) as an alternative.

**Comment by rdmdk** [comment]
@eladnava 

I had tried the Create Shortcut method before I even came across Applicationize but the unslightly toolbar atop of the app window is what put me off - and converting a webapp to a PWA adds the same toolbar - and the minimum width of the shortcut/PWA is still a bit too wide for my liking :)

I've also tried Nativefier and it generally works quite well minus the large filesize

**Comment by Genxster1998** [comment]
Its indeed not good replacement at all , i just hate electron apps to add other instance of chromium engine and other chrome pwa apps cause to launch chrome first always , make me annoyed to minimise it .Any patch exist to resolve it ?

**Comment by maxhayim** [comment]
Yeah a clients web app stopped working, had to download the official one. I knew the message was appearing for months and today it just stopped working.
