### ISSUE TITLE
Can't download items

### ISSUE THREAD

**Issue by Caleb10E** [eladnava/applicationize#16]
One of the things I made with Applicationize is a Google Photos app. It works great, except that I cannot download photos when using the Applicationize-created version. It doesn't seem like any sort of downloads work when applicationized.

**Comment by eladnava** [comment]
Hi @Caleb10E,
Welcome to Applicationize! Glad you are enjoying it so far.

Regarding file downloads, nice catch!

It looks like it's definitely possible to fix this:
http://stackoverflow.com/a/17872514/1123355

I'll try getting around to implementing the fix in the next few days.

**Comment by eladnava** [comment]
Hi @Caleb10E,
Implemented the fix and deployed it! Please try it out:
https://applicationize.me/now

Thanks again for reporting this bug!
