### ISSUE TITLE
Doesn't Seem to Respect Name Override

### ISSUE THREAD

**Issue by ambroselittle** [eladnava/applicationize#19]
I'm using this at https://applicationize.me/now. 

For URL, I use this: https://mail.google.com/mail/u/?authuser=myemail@domain.com

I provide my own PNG, and I specify "Company Gmail" as the app title. 

Actual Results:
However, when I drop it into extensions, it recognizes the title as just "Gmail" and that's what shows in the menubar (on OS X El Capitan). 

Expected Results:
I expected it to use the title I gave in the Extensions list and menubar, etc. 

Is this a bug or am I misunderstanding the title override?

**Comment by eladnava** [comment]
@ambroselittle I tried reproducing this but failed to do so.

I applicationized Gmail using the exact steps you mentioned, and it worked:

![screen shot 2016-06-10 at 5 33 38 pm](https://cloud.githubusercontent.com/assets/4394189/15967763/a4e475cc-2f31-11e6-8115-6fec11c2e8a4.png)
![screen shot 2016-06-10 at 5 33 18 pm](https://cloud.githubusercontent.com/assets/4394189/15967764/a4eb9410-2f31-11e6-9877-0f1e0fae2fae.png)

Just to verify, are you entering the title before generating and downloading the extension?

**Comment by ambroselittle** [comment]
Hi Elad,

I took a screencast so you can see exactly what I'm doing:
https://youtu.be/h61YWJjHcJ4 

Let me know if I'm doing it wrong.

**Comment by eladnava** [comment]
@ambroselittle Thanks for taking the time to record and upload that, appreciate it!

You're doing everything right -- this is extremely weird behavior.

Can you please zip up the generated `.crx` file and upload it by dropping into the GitHub issue comment textarea?

Thanks!

**Comment by ambroselittle** [comment]
[mail.google.com.crx.zip](https://github.com/eladnava/applicationize/files/309444/mail.google.com.crx.zip)

**Comment by ambroselittle** [comment]
Maybe some setting or extension is interfering. Just a thought.

**Comment by ambroselittle** [comment]
I tested in Safari with the same result (in generating the app).

**Comment by eladnava** [comment]
This is really really weird. The extension file contains "Gmail" as the extension title, which shouldn't have happened if the server received your request with a custom `title` form input.

So I'd like to see if your browser is correctly sending the title you specified within the request to generate the extension.

Please:
1) Open https://applicationize.me/now in Google Chrome
2) Enter URL and title of the extension
3) Open Chrome Developer Tools
4) Go to Network tab
5) Click "Generate & Download Chrome Extension" to submit the form
6) Right click the request labled `applicationize` within the Network tab
7) Click "Copy as cURL"
8) Paste the clipboard into a new GitHub comment

Thanks!

**Comment by ambroselittle** [comment]
curl 'https://applicationize.me/applicationize' -H 'Cookie: _ga=GA1.2.2009992299.1464997267; _gat=1' -H 'Origin: https://applicationize.me' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8,ja;q=0.6' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryZ8PgSGIoswfwCCe9' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: https://applicationize.me/now' -H 'Connection: keep-alive' --data-binary $'------WebKitFormBoundaryZ8PgSGIoswfwCCe9\r\nContent-Disposition: form-data; name="url"\r\n\r\nhttps://mail.google.com/mail/u/?authuser=me@mydomain.com\r\n------WebKitFormBoundaryZ8PgSGIoswfwCCe9\r\nContent-Disposition: form-data; name="icon"; filename="teltech_squares gmail.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundaryZ8PgSGIoswfwCCe9\r\nContent-Disposition: form-data; name="title"\r\n\r\nTelTech Gmail\r\n------WebKitFormBoundaryZ8PgSGIoswfwCCe9\r\nContent-Disposition: form-data; name="frameColor"\r\n\r\n\r\n------WebKitFormBoundaryZ8PgSGIoswfwCCe9--\r\n' --compressed

**Comment by ambroselittle** [comment]
It has something to do with the image I am using. I tried a different image, and it works. I think it has something to do with image size, because I tried another largish image (365kb) and it won't take the title. The image I was using before is 112kb. The one that worked is 8kb.

**Comment by eladnava** [comment]
@ambroselittle Excellent observation!

Any chance you can upload the problematic image here in a `.zip`?

Thanks!

**Comment by eladnava** [comment]
Never mind, got it to reproduce with a large image of my own.

It's most likely got to do with [co-busboy](https://github.com/cojs/busboy) which is supposed to parse the `multipart/form-data` and make sense out of it -- the large attachment is probably throwing it off for some reason.

Going to check it out now.

**Comment by eladnava** [comment]
@ambroselittle Fixed it, indeed the `co-busboy` package had trouble parsing the input fields sent alongside the multipart upload. Switching to [koa-better-body](https://github.com/tunnckoCore/koa-better-body) resolved this instantly, and also cleaned up the code quite a bit (no need to manually parse the request body on demand as with `co-busboy`).

Deployed the fix to production, tested it with a large attachment, and now the title changes as expected:
https://applicationize.me/now

Huge thanks for helping debug this! =) 

Enjoy Applicationize and let me know if there's anything else that could be improved!

**Comment by ambroselittle** [comment]
Yup. Seems to work. Thanks!
