### ISSUE TITLE
Add optional permissions to manifest file

### ISSUE THREAD

**Issue by mikekolganov** [eladnava/applicationize#22]
Story: When Chrome asks user for permissions on regular tab (like notifications, access to camera and min) dialog is displayed at top of the page. But applicationized extensions isn't displayed these dialogs. And to enable notifications user needs to open applicationized website in regular tab to allow required permissions.

Suggestion: allow to choose permissions on generating applicationize under "Advanced" button. Not all, just common like `audioCapture`, `videoCapture`, `notifications`, etc. and put them to manifest file along with `webview`.

Related to #13.

**Comment by eladnava** [comment]
Great suggestion @mikekolganov, any chance you'd have time to submit a PR?

**Comment by eladnava** [comment]
Anyone up for this?

**Comment by CosmicMJ** [comment]
This is desperately needed.  There are so many sites that I would applicationize if they could display notifications.

In the meantime, the following doesn't work for me.  Even if the website has full permissions and ability to display notifications via chrome tabs, the applicationized version of the website has no permissions, and fails to prompt for them.
> And to enable notifications user needs to open applicationized website in regular tab to allow required permissions

**Comment by eladnava** [comment]
Either resolving #25 or submitting a PR to add optional permission support would resolve this. Anyone up for this? :

**Comment by eladnava** [comment]
This has now been implemented in https://github.com/eladnava/applicationize/commit/6ee21600e61a7f7b0d580826f1d237651412d53f!

The following permissions can now be granted in the Advanced Options section of https://applicationize.me/now:
`audioCapture`
`videoCapture`
`notifications`

If there are any other permissions you would like to be able to control, let me know! 👍
