### ISSUE TITLE
Smooth scrolling on Applicationize website

### ISSUE THREAD

**Issue by mondaiguy** [eladnava/applicationize#23]
This isn't really an issue but I can't figure out how to contact you.

How did you make it so scrolling with a scroll wheel is so smooth on your website (Safari tested)?

Is this a CSS setting I could add to a global stylesheet maybe?

**Comment by eladnava** [comment]
Hi @mondaiguy,
This is actually built-in functionality in the Foundry theme:
https://themeforest.net/item/foundry-multipurpose-html-variant-page-builder/11562108

I'm actually not sure how they did that -- wasn't able to find any JavaScript code that would cause that behavior, nor any CSS declarations. If you have the time, eliminate resources one at a time from the [index.html](https://github.com/eladnava/applicationize/blob/master/public/index.html) and wait for the effect to disappear. This will help you narrow down the search.

**Comment by mondaiguy** [comment]
Surely it's <script src="js/smooth-scroll.min.js"></script> ?

**Comment by mondaiguy** [comment]
"script src="js/smooth-scroll.min.js"></script"

**Comment by mondaiguy** [comment]
Looks like this works for adding smooth scrolling OS wide. Even works on macOS Sierra.

https://www.smoothscroll.net/mac/
