### ISSUE TITLE
Google drive opens google docs/sheets/etc. in new window instead of same window.

### ISSUE THREAD

**Issue by guidokok** [eladnava/applicationize#31]
Can you make an option in Avdanced options, to make all links, except for pop ups, open in the same application window?   (When I now open a google document it tries to open safari instead of opening it in the same window).

**Comment by eladnava** [comment]
@guidokok Do you mean in a new window (but not in a Chrome tab)? Applicationize doesn't have a tab system, but it can open another identical window to itself with the target URL.

**Comment by guidokok** [comment]
I understand applicationize doesn't have a tab system for obvious  reasons. It would be great if it just navigated to the google doc in the same page or another identical window. But it doesn't do that. Instead it launches a new window with the OS standard browser. (on mine, that's safari)

**Comment by eladnava** [comment]
Added the option: 

![screen shot 2016-11-30 at 12 39 16 pm](https://cloud.githubusercontent.com/assets/4394189/20749190/0a55834c-b6fa-11e6-83de-8dd73c8b76c7.png)

Deployed to applicationize.me/now.

**Comment by guidokok** [comment]
Fucking awesome! You are a cloud hero!!

**Comment by eladnava** [comment]
My pleasure! If you'd like to donate to keep the project alive, check out #32.
