### ISSUE TITLE
Google contacts in consumer Gmail doesn't open.

### ISSUE THREAD

**Issue by guidokok** [eladnava/applicationize#33]
When it opens, it doesn't load google contacts and only shows an empty window.

**Comment by eladnava** [comment]
Hi @guidokok,
Can you please post a screenshot and more detailed explanation?

Thanks!

**Comment by eladnava** [comment]
Does that window show `about:blank` in the address bar? 

Looks like a duplicate of #36.

**Comment by guidokok** [comment]
I think it's about:blank but I cannot verify as your app doesn't show the address bar.

**Comment by eladnava** [comment]
Closing for now as this appears to be a duplicate of #36.
