### ISSUE TITLE
Drag & Drop in Dropbox doesn't work

### ISSUE THREAD

**Issue by guidokok** [eladnava/applicationize#34]
I can select multiple files or folders, but when dragging it onto another folder, it doesn't do anything and no move is performed. In a normal chrome window it does work.

**Comment by eladnava** [comment]
Hi @guidokok,
How are you? Hope you are doing well.

I just tried to drag and drop a file into a Dropbox folder in an Applicationize window and it worked:

![test](https://cloud.githubusercontent.com/assets/4394189/21868158/25e0d888-d85a-11e6-85c2-a086b2665115.png)

Does yours not show the icon like mine does? When I released the mouse it moved the file successfully.

**Comment by guidokok** [comment]
Doesn't work, see here:

http://recordit.co/hJwS3L4VNl


Hartelijke groet,

Guido Kok  <http://www.twitter.com/guidokok>
<http://nl.linkedin.com/in/guidokok1/nl>
*T:* +31-20-2050430 <+31202050430>
Q: Why is this email five sentences or less?
A: http://five.sentenc.es
<http://www.conexes.nl>

**Comment by eladnava** [comment]
Try to drag from the file name link into the folder name link and not from their backgrounds and let me know if it works 👍

**Comment by guidokok** [comment]
That works, Thanks.

Hartelijke groet,

Guido Kok  <http://www.twitter.com/guidokok>
<http://nl.linkedin.com/in/guidokok1/nl>
*T:* +31-20-2050430 <+31202050430>
<http://www.conexes.nl/>

Op 12 jan. 2017 om 12:01 heeft Elad Nava <notifications@github.com> het
volgende geschreven:

Try to drag from the file name link into the folder name link and not from
their backgrounds and let me know if it works 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/eladnava/applicationize/issues/34#issuecomment-272135376>,
or mute the thread
