### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by d1verjim** [eladnava/applicationize#35]
Hi there,

I am using applicationize on a Macbook Pro - OSx Sierra - to have gmail & google calendar as a standalone app.

However, the Back function of Chrome doesn't work - neither CMD-left arrow, nor mouse shortcut.

Is this a know limitation?

Thanks.

**Comment by eladnava** [comment]
Try `Cmd` + `{`. 👍

**Comment by d1verjim** [comment]
Thanks.  That works, although it does left align / right align if you're actually in a text box.

Any reason it's not the default cmd + left?

Also (and apologies, this is really a totally separate issue), Links to google hangouts from Google Calendar just open an "about:blank" tab.  If you right click, inspect, then "Open in new tab" from the devtools menu then it works, but that's not ideal.

**Comment by eladnava** [comment]
Unfortunately, looks like this is because Gmail first opens an `about:blank` window and then changes its location object.

Doesn't look like this is easily fixable.

More information here:
https://github.com/eladnava/applicationize/issues/18#issuecomment-223762312
