### ISSUE TITLE
Show URL bar?

### ISSUE THREAD

**Issue by robertgranholm** [eladnava/applicationize#37]
I often copy and paste the URL bar in Gmail to refer back to a specific email later, is there anyway to capture the URL, or re-add the URL bar?

**Comment by eladnava** [comment]
Currently no, but we might add this in the future if there is enough demand as an optional setting.

**Comment by eladnava** [comment]
Also related: #40.

**Comment by claytonolley** [comment]
I would definitely like this feature as well. I know this app is meant for SPA sites etc, but back/forward functionality would be good as well.

**Comment by eladnava** [comment]
@claytonolley I'm pretty sure back/forward works via `Ctrl + {` and `Ctrl + }`.

**Comment by eladnava** [comment]
@robertgranholm You can now copy the current page URL via `CMD + L`: #40.

**Comment by eladnava** [comment]
Closing this issue for now as #40 is a good workaround in my opinion. If you feel different, please let me know. 👍
