### ISSUE TITLE
Window frame color slightly different

### ISSUE THREAD

**Issue by mammuth** [eladnava/applicationize#38]
I wanted to color the frame of my _inbox.google.com_ app to be the same as the header-color of the webapp. 
By inspecting the website with the dev tools, you see that the color is `#4285f4`. However, when setting this color when creating the packaged app, the result isn't 100% the same. 

Maybe the window frame changes the color in some way or overlays something?

![image](https://cloud.githubusercontent.com/assets/3121306/26006944/af7e27d8-373e-11e7-8354-8c3c60776d10.png)

**Comment by mammuth** [comment]
![image](https://cloud.githubusercontent.com/assets/3121306/26007112/75a653cc-373f-11e7-8cff-b146aed8e0f9.png)
Hm, when doing the same with web.whatsapp.com it's correct. So looks like the inbox webapp changes the color somehow 🙈

**Comment by eladnava** [comment]
Interesting, thanks for reporting your findings. 👍
