### ISSUE TITLE
Support for Camera and Microphone?

### ISSUE THREAD

**Issue by nigelellis** [eladnava/applicationize#41]
I'd like to use this to build a custom app for my company meeting hangouts.   When I install the extension it looks like there's no access to Camera or Microphone settings.  Is this a limitation of extensions, or something that can be addressed by requiring more permissions?

Thanks, really appreciate the effort you've put into this utility.

Nigel.

**Comment by eladnava** [comment]
Hi @nigelellis,
Looks like two things need to be done for this to work:
1) Including the necessary permissions in the extension manifest (`audioCapture` / `videoCapture`)
2) Listening for `permissionrequest` event on `webview` and permitting the request automatically

More info:
http://stackoverflow.com/a/28089600/1123355

I think we should hide this behind a toggle which is by default disabled within the Advanced Options in the applicationize.me/now form.

**Comment by nigelellis** [comment]
Elad, thank you for following up on this - really appreciate it.

**Comment by eladnava** [comment]
My pleasure!

This has now been implemented in https://github.com/eladnava/applicationize/commit/006839b3fe7a92d2b530f9338ec1f79700838faa and deployed to https://applicationize.me/now. 👍

**Comment by nigelellis** [comment]
Awesome, thank you!
