### ISSUE TITLE
website refresh?

### ISSUE THREAD

**Issue by melonista** [eladnava/applicationize#43]
Hi,

Thanks for this repo.

I have one question: Is there a way of setting an auto-refresh in the generated apps? I know there are chrome extensions that do that, but don't know if/how use one of these in here.

Thanks!

PS: I'd also be interested in an optional auto-scrolling down when the app is opened... but I guess that is too specific!

**Comment by eladnava** [comment]
Hi @melonista,
I'm happy you like Applicationize!

At this time, we don't support auto-refresh or auto-scroll. Also, these seem to be custom-tailored features which may not benefit all of our users. 

Therefore, unless more people would comment in this issue that it they would love for any of these features to be implemented as well, I don't think they should be implemented in this repository.

However, feel free to clone the repository and make any changes there! You would essentially need to edit [background.js](https://github.com/eladnava/applicationize/blob/master/assets/crx/js/background.js) and make it refresh the `<webview>` every X seconds using `setInterval()`, and similarly to auto-scroll the page down.

Then, you would generate an extension off of your own `localhost:3000` Applicationize server and use that. 

Good luck 👍

**Comment by claytonolley** [comment]
How do we manually refresh a page?

Sent from my iPhone

On May 24, 2017, at 3:13 PM, Elad Nava <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @melonista<https://github.com/melonista>,
I'm happy you like Applicationize!

At this time, we don't support auto-refresh or auto-scroll. Also, these seem to be custom-tailored features which may not benefit all of our users.

Therefore, unless more people would comment in this issue that it they would love for any of these features to be implemented as well, I don't think they should be implemented in this repository.

However, feel free to clone the repository and make any changes there! You would essentially need to edit background.js<https://github.com/eladnava/applicationize/blob/master/assets/crx/js/background.js> and make it refresh the <webview> every X seconds using setInterval(), and similarly to auto-scroll the page down.

Then, you would generate an extension off of your own localhost:3000 Applicationize server and use that.

Good luck ?

-

**Comment by eladnava** [comment]
This has been implemented via CMD + R in https://github.com/eladnava/applicationize/commit/12ac7a344a9abd5b3f15ff40ff5d326958e3a207. 👍
