### ISSUE TITLE
Find functionality missing (ctrl + f not working)

### ISSUE THREAD

**Issue by heiba** [eladnava/applicationize#44]
Hello,

First of all, well done on creating Applicationize, within 2 days of getting my mac, it's now my most-used app.

However, one big missing feature is: ctrl+f , the find functionality doesn't work unfortunately.

You know how essential the find functionality is in many web apps, I don't really need to mention the million use cases when Applicationizing Wikipedia, Google Keep, Facebook, etc

Let me know if there's a work around please

Thanks

**Comment by claytonolley** [comment]
I second this request.

**Comment by eladnava** [comment]
Thanks for your kind words!

It appears to be possible to implement this, but would require that we either migrate back to a hosted app (#25) or that you try the following:
1) Go to the target website
2) Click the three vertical dots in the top right of Chrome
3) More Tools -> Add to Applications
4) Tick `Open as window`

This type of app is a workaround for Applicationize and does support Ctrl + F.

**Comment by heiba** [comment]
Hello Elad,

Can you not use the existing chrome find function in Applicationize ?

The work around you provided doesn't apply on mac -> hence why I am using Applicationize

**Comment by eladnava** [comment]
Hi @heiba,
Sorry, I forgot to mention that you must enable the following Chrome flags (chrome://flags/):

1) The new bookmark app system
2) Allow hosted apps to be opened in windows
3) Creation of app shims for hosted apps on Mac

**Comment by eladnava** [comment]
I have went ahead and implemented this into Applicationize! 🎉 

The key combination `CMD + F` now brings up a simplified find box with very similar behavior to Chrome's native find functionality:

![screen shot 2017-06-02 at 3 38 00 pm](https://cloud.githubusercontent.com/assets/4394189/26725927/7e27d62c-47a9-11e7-8dce-f2191199c9a7.png)

**Comment by heiba** [comment]
Amazing work!! Tested it, and it works great! Please also make CMD + F hide the find box if already visible!

**Comment by eladnava** [comment]
@heiba Press Escape to hide the find box. On Chrome, pressing CMD + F does not hide the open box.

Regarding find-as-you-type, done! 👍

**Comment by heiba** [comment]
You're superb @eladnava , find-as-you-type working like a charm!

**Comment by heiba** [comment]
Pressing Escape in Applicationize while in fullscreen will exit full screen, then I need to press escape again to hide find box.

In chrome, pressing escape while in full scree, will hide find box and will not exit full screen.

Could you possibly resolve this inconvenience please :)

**Comment by eladnava** [comment]
Hi @heiba,
I tried to reproduce this on YouTube in full screen mode but failed.

Which site with full screen mode are you experiencing this on?

**Comment by heiba** [comment]
Try messenger.com, keep.google.com, any website i tried with really

**Comment by eladnava** [comment]
Hi @heiba,
How do you enter full screen mode in those websites? There is no UI control for this.

**Comment by heiba** [comment]
hi @eladnava , I believe there is a misunderstanding. Any window in Mac can go to full screen if you click on the green button, which makes the window full screen and shifts it right in its own space screen in Mac.

This is Google Keep applicationized in normal mode

<img width="313" alt="screen shot 2017-06-06 at 12 51 42 am" src="https://cloud.githubusercontent.com/assets/4654411/26802683/7bd000ba-4a52-11e7-81a6-5f33e81a068a.png">

This is Google Keep applicationized in fullscreen mode

<img width="398" alt="fullscreen1" src="https://cloud.githubusercontent.com/assets/4654411/26802702/910fa3d6-4a52-11e7-92b4-9095c9fd66cf.png">

This is Google Keep applicationized in normal mode and I hover to display the menu bar at the top

<img width="345" alt="screen shot 2017-06-06 at 12 52 02 am" src="https://cloud.githubusercontent.com/assets/4654411/26802707/97d26550-4a52-11e7-97d1-b4b4e7075736.png">

**Comment by eladnava** [comment]
Hi @heiba,
Thanks for the detailed explanation. I was able to reproduce your issue. 

It appears that Chrome packaged apps in full screen mode cannot listen for the `Escape` key until the full screen mode is minimized. 

So, I think a workaround would be to add a `X` icon in the find box. What do you think?
