### ISSUE TITLE
Zooming doesn't work on Windows

### ISSUE THREAD

**Issue by creayt** [eladnava/applicationize#46]
Guessing it's because you've implemented the command key only ( docs seemed to only reference that ). Love your app so far but I'm finding it unusable w/ the main site I'm using it for ( Asana ) without being able to zoom to make the text a readable size on high res ( 4k ) screens. Thanks!

**Comment by eladnava** [comment]
Hi @creayt,
This appears to have been fixed, please confirm by re-applicationizing Asana.
