### ISSUE TITLE
browser Back keyboard shortcut

### ISSUE THREAD

**Issue by eugenefine** [eladnava/applicationize#47]
add support for browser Back keyboard shortcut key

**Comment by eladnava** [comment]
@eugenefine Chrome no longer navigates backward when you press `Back`. More info:
https://venturebeat.com/2016/08/14/restore-backspace-shortcut-chrome/

Apparently a lot of users have lost a lot of form data by accidentally hitting Backspace when an input is not focused.

Use `Cmd/Ctrl + {` and `Cmd/Ctrl + }` instead.

Closing as I do not think we should implement this.

**Comment by eugenefine** [comment]
thank you for clarification. I did not realize 'Cmd/Ctrl + {' and 'Cmd/Ctrl + }' are working. I just tested it and it works great! thank you.
