### ISSUE TITLE
Javascript alert windows are not displaying on mac

### ISSUE THREAD

**Issue by eugenefine** [eladnava/applicationize#48]

**Comment by eladnava** [comment]
Hi @eugenefine,
Thanks for the report!

It appears alert and confirmation dialogs are blocked by default in Chrome `<webview>` elements, which is what Applicationize uses under the hood.

The solution is to listen for the `dialog` event and display a custom popup box with text:
https://stackoverflow.com/a/30549457/1123355

Would you be interested in implementing this?

Please consider this as a possible workaround:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260

**Comment by eugenefine** [comment]
unfortunately, not going to be able to help, since I am not a developer :(

**Comment by eladnava** [comment]
That's no problem. Anyone else? Similar to what I did here for implementing a Find in Page UI box:
https://github.com/eladnava/applicationize/commit/104bc3161068aaf99b040fc8abaa863d04453bc2

**Comment by eladnava** [comment]
Closed via #50.
