### ISSUE TITLE
Won't work with Google login for third party Apps

### ISSUE THREAD

**Issue by bobharpista** [eladnava/applicationize#51]
I used this for Asana. To login to https://app.asana.com I use my google login. I don't have a username and password as a backup, Google is the only way for me to access Asana. It will not work using your app. The first time I tried it pulled up a separate screen, I input my google credentials, and clicked login. After that it just went to a blank white screen. Let me know if this can be resolved. Thanks!

**Comment by eladnava** [comment]
This is caused by #36.

Here is a workaround:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260

**Comment by bobharpista** [comment]
Thanks for the reply! I'm not sure if it matters but I am on Win 10. Either the workaround doesn't work anymore or I don't understand what to do. I can't find anything about "shims" or the "new bookmark app system" in chrome://flags. I also don't see any hamburger/menu icon on that page. No worries if it is way above my level, but I figured I'd ask.

**Comment by eladnava** [comment]
Hi @bobharpista,
If you are on Windows, you do not need to enable these flags. They are for OSX only.

You already have Applicationize built-in to Chrome. Here's where it's at:
![](http://slashgenie.com/wp-content/uploads/2015/09/Chrome-Add-To-Taskbar-Windows-10.jpg)

**Comment by bobharpista** [comment]
Thanks!
