### ISSUE TITLE
If 'Would you like external links to open internally as popups?' is disabled, then you will never be able to create or open another document from the File menu in Google Docs / Sheets

### ISSUE THREAD

**Issue by Zuldra** [eladnava/applicationize#54]
Hello and thanks for this nice tool.

I'm attempting to use Applicationize for Google Sheets and Google Docs.

If the 'Would you like external links to open internally as popups?' option is disabled.. and then you attempt to create a New document or to Open a document from the File menu in Google Docs, it will always fail and open in an external browser instead.

You are effectively forced to stay on the first document you opened forever, until you quit the app and restart from scratch again. Very difficult to work like that.

The alternative is to set 'Would you like external links to open internally as popups?' to enabled, which allows another document to be opened beyond the first one. But this also forces all external links to be opened within the Applicationize app window.

Neither solution is appropriate.

A solution to this problem would be to allow a certain host mask to be exempt from opening as external links. In this example, I would set 'docs.google.com' to be exempt, so that all URL's opening there will stay inside the app.

I hope this can be resolved when the App is hosted again.

Thanks

**Comment by eladnava** [comment]
Hi @Zuldra,
Thanks for this suggestion!

Only app links with the same hostname as the applicationized window will now open internally, if the option is enabled when generating the extension, as per https://github.com/eladnava/applicationize/commit/39477c761344117eae3e8185a5695d440c53702a.
