### ISSUE TITLE
Google Voice 401

### ISSUE THREAD

**Issue by TheFunkyMonk** [eladnava/applicationize#56]
Hey, thanks for the great app. I noticed an issue trying to create a Google Voice app with Applicationize: it loads the landing page at `https://voice.google.com/u/0/about`, but when you click "Sign In", it throws a 401 error trying to load `https://voice.google.com/signup`.

Here's a screenshot of the network headers:

<img width="610" alt="screen shot 2017-08-15 at 9 15 04 pm" src="https://user-images.githubusercontent.com/1728770/29347130-1e50a5e0-81ff-11e7-8ff0-201d157376ba.png">

**Comment by eladnava** [comment]
Hi @TheFunkyMonk,
I am unable to reproduce. Maybe this was a temporary server error on Google's end?

I applicationized the following URL:
```
https://voice.google.com/u/0/promo
```

**Comment by TheFunkyMonk** [comment]
Hey @eladnava, thanks for the reply. Did you try clicking on the "sign in" option on the top right? I just tested again with the url you provided, but after clicking "sign in" I get the same 401 error.

**Comment by eladnava** [comment]
Hi @TheFunkyMonk,

Yes, it led me to the Google Sign In page:

![screen shot 2017-08-16 at 10 27 55 pm](https://user-images.githubusercontent.com/4394189/29381537-2db2cdf0-82d2-11e7-9bf3-2948b40d0ee1.png)

**Comment by TheFunkyMonk** [comment]
Oh weird! Must be something with my network or machine then, thanks for checking into it.

**Comment by eladnava** [comment]
Sorry for not being able to help! If you figure out why it's happening, let us know. 👍

**Comment by heyitsbryanm** [comment]
@TheFunkyMonk , if you figure it out can you let me know? I'm also seeing the same problem.

**Comment by TheFunkyMonk** [comment]
Hey @heyitsbryanm, I know it's been a while, but I just tried making a Voice app with the latest build of Electron, and it seems to work fine now. Here's my app if you still need one: https://drive.google.com/open?id=1_36MrzXBBZXCjRQbHRL62Cp2DSkqwxB-
