### ISSUE TITLE
Whitelist/blacklist in-app URL patterns instead of just hostname

### ISSUE THREAD

**Issue by Trinition** [eladnava/applicationize#57]
Instead of relying on the parsed URL hostname to determine if a URL is in-app or not, allow custom URL patterns.  This is how FluidApp does it, for example.

Suppose you have an internal corporate network with both Atlassian HipChat and Atlassian BitBucket hosted at virtual paths behind a server:

- http://intranet/hipchat
- http://intranet/bitbucket

If each is desired to be run in it's open Applicationized app, just the hostname won't work.

**Comment by eladnava** [comment]
Hi @Trinition,
Are you referring to the external link feature which opens non-hostname links in a new Chrome window instead of an Applicationize window?

**Comment by eladnava** [comment]
Closing due to lack of response. Please feel free to comment if you still need help with this.
