### ISSUE TITLE
True fullscreen (toggle title bar off) in Windows

### ISSUE THREAD

**Issue by bovafett** [eladnava/applicationize#58]
Elad,

Love this project. Have started using it to run a containerized version of Asana's webapp.

I run the app full screen, and would like to know if there's a way to hide the title bar entirely. Slack does this with their chromium powered desktop app, so I wondered if there's a way you might be able to add that feature (or if there's some keyboard shortcut that I don't know about).

That'd make it truly seamless and help a ton.

Thanks!

**Comment by eladnava** [comment]
Hi @bovafett,
Happy to hear!

Commit https://github.com/eladnava/applicationize/commit/e7d0698938691208981f968cf18ebb4d4e582e09 makes it possible to toggle full screen mode by pressing `ALT + CTRL + F`. Make sure to recreate your application though:
https://applicationize.me/now
