### ISSUE TITLE
Why can't I add extensions directly from the website?

### ISSUE THREAD

**Issue by talha131** [eladnava/applicationize#6]
Thank you for creating this useful app.

I have to download extension separately and install them by dragging over extensions page. When I try to install them by double clicking the download I get this error.

<img width="688" alt="screen shot 2016-01-31 at 17 40 57" src="https://cloud.githubusercontent.com/assets/1094724/12702174/1a0c61c2-c842-11e5-8a17-27d9082af5e5.png">

How can I go around this error?

**Comment by eladnava** [comment]
Yeah, that's a known issue unfortunately. Google Chrome doesn't permit installing Chrome Extensions from unknown third-party websites. That's why it displays this message, and I'm pretty sure there's no way around it -- you'll have to manually drag the `.crx` into the `chrome://extensions` page.

**Comment by talha131** [comment]
Thank you for the explanation.

**Comment by toobulkeh** [comment]
How do you even get the .crx file? I just get a warning with "Discard" as the only option?

**Comment by eladnava** [comment]
Hi @toobulkeh,
Can you please take a screenshot?

**Comment by toobulkeh** [comment]
Thanks for the fast response @eladnava -- I fixed it by restarting chrome (which updated to the latest version). Apparently if a chrome window is in a non-updated state, the "Continue" button (on the bottom bar when downloading) just doesn't show up -- nor do any popups.

**Comment by eladnava** [comment]
Cool, thanks for letting us know 👍
