### ISSUE TITLE
Internal scrollbar isn't scrollable via mousewheel (facebook)

### ISSUE THREAD

**Issue by heyitsbryanm** [eladnava/applicationize#60]
The internal scroll bar for Facebook messenger isn't working via mouse wheel. You can see this issue here:
https://www.screencast.com/t/bwOcMisPJ

I don't know how to get any other useful information for this, but here's the app I created for it:
[www.facebook.com.zip](https://github.com/eladnava/applicationize/files/1288563/www.facebook.com.zip)

**Comment by eladnava** [comment]
Hi @heyitsbryanm,
Thanks for taking the time to report and screencast this issue.

Unfortunately I can't reproduce this on OS X, so it might be a Windows-only issue. 

Can you also try updating your Chrome version to see if that fixes the issue?

**Comment by eladnava** [comment]
Closing due to lack of response. Please feel free to comment if you still need help with this.
