### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by tosinafolabi** [eladnava/applicationize#61]
Hi,

Thanks for this repo.

For some reason, the following keyboard shortcuts don't work on "applicationized" apps:

``CMD + +`` to zoom in
``CMD + -`` to zoom out
``CMD + 0`` to reset zoom
``CMD + R`` to refresh the page
``CTRL + CMD + F`` to enter full screen mode

(as tested on MacOS 10.13).

Perhaps, take a look?

**Comment by eladnava** [comment]
Hi @tosinafolabi,
Just tested all of these shortcuts and they all work for me. It's worth mentioning that I'm on Sierra and haven't updated yet, so maybe High Sierra is causing this?

**Comment by tosinafolabi** [comment]
@eladnava,

Thanks for the feedback. I'll try the extensions on a Sierra setup and report back.

**Comment by WojtekKruszewski** [comment]
I'm experiencing this too on High Sierra & Chrome 61.0.3163.100 64-bit.

**Comment by eladnava** [comment]
I currently do not have access to a computer running High Sierra to reproduc this, I'll try to get my hands on one in an Apple store but not sure when that'll be.

**Comment by Philipp8765** [comment]
Hi @eladnava 

Thank you for taking care of this issue.

Unfortunately on my Setup OS X El Capitan 10.11.5 and Chrome 61.0.3163.100 it does not work either.

I'm able to zoom (cmd - ;cmd + ;cmd 0) and search (cmd f) after I startet the applicationize app until I click anything. After that it does not work anymore.

greetings 
Philipp

**Comment by eladnava** [comment]
Hi @Philipp8765,
My pleasure. What is the applicationized web app URL?

**Comment by Philipp8765** [comment]
Hey @eladnava 

Thank you for the very fast response! 

Unfortunately you won't be able to open it, because it is a closed social Intranet webapp called Bitrix24. Zooming and refresh the content is essential to the usability. As well as not having it between 30 open browser tabs – so applicationize is a beautiful idea! 

I experience exactly the same behavior with https://www.youtube.com. 

It would be great to get it fixed somehow! 

Thanks in advance!

**Comment by eladnava** [comment]
I have managed to reproduce the issue and deploy a fix in I have managed to reproduce the issue and deploy a fix in https://github.com/eladnava/applicationize/commit/82a9ae70b0cf6d2f2815767baa98bbf355ae4589. 👍

**Comment by eladnava** [comment]
I have managed to reproduce the issue and deploy a fix in https://github.com/eladnava/applicationize/commit/82a9ae70b0cf6d2f2815767baa98bbf355ae4589 🎉 

Please make sure to regenerate your app(s) via https://applicationize.me/now 👍

**Comment by Philipp8765** [comment]
Thank you very much! 

It works without issues.

**Comment by tosinafolabi** [comment]
Hi @eladnava 

Thanks for the fix.

**Comment by eladnava** [comment]
Cheers guys, my pleasure 👍
