### ISSUE TITLE
Fake User Agent?

### ISSUE THREAD

**Issue by drumstix1020** [eladnava/applicationize#64]
Is there a way to fake the user agent to be mobile? I have a website that only runs on mobile browsers, but I have a chrome extension that fakes the user agent on that specific website domain. I'd love to make that site a standalone app, but browser extensions don't carry over to the apps made with applicationize so i get locked out every time. If there's a way to do this that would be amazing!

**Comment by eladnava** [comment]
Hey @drumstix1020,
Thanks for this suggestion!

This is now possible via commit https://github.com/eladnava/applicationize/commit/3ea0643b18e41be63aa00ac28e8e0bb1e2983e0c! 🎉
