### ISSUE TITLE
Photopea.com popups always external

### ISSUE THREAD

**Issue by GospelNerd** [eladnava/applicationize#67]
- Create an extension using https://photopea.com 
- Toggle "Would you like app links to open internally as popups?"
- Open app
- Click "Login" (on the top bar)
- Popup opens in Chrome, preventing login in the app window

**Comment by GospelNerd** [comment]
The problem is the popup is opening "www.photopea.com". This should be handled the same as a link with the same exact hostname.

**Comment by eladnava** [comment]
Hi @GospelNerd,
Can you please try to generate a new extension for this website with the `www.` subdomain?

```
https://www.photopea.com
```

Please don't forget to toggle "Would you like app links to open internally as popups?".

**Comment by GospelNerd** [comment]
Yes, that works. But, I just think on background.js line 69 when you check for hostname you can also check for www. as it's pretty commonly prepended, or even better figure out how to match all subdomains (maybe add that as a config preference?).
