### ISSUE TITLE
ability to set name and icon

### ISSUE THREAD

**Issue by jtoy** [eladnava/applicationize#68]
I have a particular google spreadsheet for my url and the name of the app shows up as "google sheets". can we add the ability to set the name and icon when generating the chrome plugin  to anything we want to better separate our web apps?

**Comment by eladnava** [comment]
You can override the app name and icon by clicking `(advanced options)` when generating your extension:
https://applicationize.me/now

**Comment by jtoy** [comment]
I see it now, it’s pretty small, might be good to enlarge it.

**Comment by eladnava** [comment]
Done. 👍
