### ISSUE TITLE
Integrating with O365 Word

### ISSUE THREAD

**Issue by kaiserkeiser** [eladnava/applicationize#74]
I've Applicationized Word using this URL:

https://www.office.com/launch/word?auth=2

this resolved in Applicationized to the 'Front Page' of word where i can see all my docs. However if i click on a doc it opens up back in the web browser, not in Applicationize. Have tried "Would you like app links to open internally as popups?" however no change.

**Comment by eladnava** [comment]
Hi @kaiserkeiser,
Make sure that you have completely uninstalled the previous extension generated by Applicationize before installing the new one with the `Would you like app links to open internally as popups?` option enabled. Then, make sure to open the new extension app and see if it works.

**Comment by kaiserkeiser** [comment]
Hi @eladnava 
Thanks for getting back to me. 

uninstalled the previous version by right-clicking the icon in Apps in Chrome and selecting "Remove from Chrome". 

then checked in Chrome://extension that the app was no longer there. 

created a new extension in Applicationize.me with the Would you like app links to open internally as popups? option.

Logging onto Word and selecting New Doc, i get redirected to a new Chrome tab with about:blank in the search bar.

**Comment by eladnava** [comment]
Ah, that explains it. Unfortunately this is a known issue documented in #36.

Possible workaround:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260
