### ISSUE TITLE
Google Keep Authentication Failure

### ISSUE THREAD

**Issue by nobodyawesomer** [eladnava/applicationize#75]
Applicationize doesn't work with Google Keep, when opening the app all I see is:

![googlekeep](https://user-images.githubusercontent.com/23288449/48453500-9f4c6880-e768-11e8-9441-52dfe2cacece.png)
Error 401

Steps to reproduce:
Regular steps to create an app, with [https://keep.google.com/](https://keep.google.com/)

**Comment by eladnava** [comment]
Seems to work for me:
![screen shot 2018-11-14 at 11 54 43 am](https://user-images.githubusercontent.com/4394189/48459154-361a3300-e804-11e8-9006-9f79aabe90c0.png)

Also logging in works and all my notes are displayed.

Are you using any proxy of some sort?

**Comment by AwesomeAlexander** [comment]
No proxy or VPN on.

I just, by accident, found a somewhat weird solution:

If I regularly clicked on the app from my chrome://apps menu, it didn't work and gave me the previous Error 401. But if I command+clicked on it (chrome keyboard shortcut for open in new tab), it opened regularly and showed me the google login screen. Now I'm logged in, I can now reopen regularly and it works fine.

Seems like strange behavior to me, any ideas why that might be happening? Just out of curiosity.
