### ISSUE TITLE
Bug - Cannot decode icon.png on Windows 10

### ISSUE THREAD

**Issue by SimpleBinary** [eladnava/applicationize#80]
I was trying to test out the website and I wanted to make an app for [Hextent](https://hextent.github.io) and It could not process the icon.png file.

**Comment by eladnava** [comment]
Hi @SimpleBinary,
That's probably because their [favicon.png](https://hextent.github.io/favicon.png) is `2362x2362` dimensions. 😆 

If you use Applicationize on any other web app (e.g. `gmail.com`) does the favicon work on Windows 10?

**Comment by SimpleBinary** [comment]
@eladnava Yes gmail does, you must be right about the icon size. Thank you.
