### ISSUE TITLE
How can i publish this chrome app to chrome store?

### ISSUE THREAD

**Issue by subratasmallik** [eladnava/applicationize#82]

**Comment by eladnava** [comment]
Hi @subratasmallik,
The Chrome apps that you generate with Applicationize cannot be published to the Chrome Web Store as Google has decided to only make these available to Chrome OS users:

```
Starting in late 2016, newly-published Chrome apps will only be available to users on Chrome OS. Existing Chrome apps will remain accessible on all platforms, and developers can continue to update them.
```
https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

If you want a friend to have the same Applicationize app as you, you can send them the `.crx` file you downloaded from applicationize.me/now and have them install it in `chrome://extensions/`.
