### ISSUE TITLE
User css?

### ISSUE THREAD

**Issue by Yzrsah** [eladnava/applicationize#83]
We can't load extensions... But could there at least be a way to load some user CSS? I want to fix an issue / adjust something.

I would not mind uploading the CSS at the time of App creation.

**Comment by eladnava** [comment]
Hi @Yzrsah,
Thanks for submitting this request. I do believe this is quite a specific request that would be highly beneficial for you but not for many other Applicationize users.

Therefore, I highly recommend simply cloning this project and injecting your CSS by calling `webview. insertCSS`:
https://developer.chrome.com/apps/tags/webview#method-insertCSS

E.g.:
```
    webview.insertCSS('html,body{ background-color: #FF0000 !important;}')
```

You can call this method in the `contentload` event:
https://github.com/eladnava/applicationize/blob/62530b1aef4f74d9624cf8c785a2f8019a534e39/assets/crx/js/embed.js#L94-L98

**Comment by Yzrsah** [comment]
```
brew install openssl
```

```
export PATH=/usr/local/opt/openssl/bin:$PATH
npm start
```

It crashes when downloading the extension:

```
fs.js:142
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:142:11)
    at Object.unlink (fs.js:960:14)
    at /foo/applicationize/node_modules/pem/lib/pem.js:928:20
    at Array.forEach (<anonymous>)
    at /foo/applicationize/node_modules/pem/lib/pem.js:927:22
    at done (/foo/applicationize/node_modules/pem/lib/pem.js:868:21)
    at ChildProcess.<anonymous> (/foo/applicationize/node_modules/pem/lib/pem.js:883:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by eladnava** [comment]
Try running on Node v4.x.

**Comment by Yzrsah** [comment]
It works on Node v6.16.0

But for some reason, the insertCSS does not work and any stuff I add to contentload event in embed.js is never called.
Can't get a console.log output
