### ISSUE TITLE
Deploy the app to Start Menu's on a Domain?

### ISSUE THREAD

**Issue by tmowreader** [eladnava/applicationize#84]
Hello!  Applicationize is GREAT first off.  Thank you for creating it.  Second.  I'd like to push an app to the start menu of the users in my domain.  Do you know if this is possible?  I've been searching the internet for hours to figure this out.

(Really all I need is Chrome to open a certain webpage and for the Start Menu shortcut to have a specific icon for each app.  But, the Google logo takes over each time you use the typical "\path to chrome.exe "Website address".  So, I've this tool to create the app and I can manually pin it to one users Start Menu and successfully give it a specific icon, but I don't see how I can deploy it via GPO or SCCM to my organization.

I realize this is a "Post app" issue, I am just desperate to figure this out.  I'm at like 20+ hours of trying to make this work in various ways.  

Thank you for your time,

Tyler

**Comment by eladnava** [comment]
Hi @tmowreader,
I think the only way to really deploy this to users of your organization would either be to deploy the `.crx` file generated by Applicationize and have them manually install it, or ship a Chrome install which already includes the extension preinstalled, or ship an image of the OS which includes an installed Google Chrome with the extension preinstalled.

That all depends on whether you have the access to do any of these.

**Comment by tmowreader** [comment]
I am the one building the image so that is totally doable.  Are there
instructions for adding the extension during the install for Chrome?  That
would be PERFECT!  That is a great idea!  Thank you!

**Comment by eladnava** [comment]
Hi @tmowreader,
Nope, that is impossible.

If you are building the image yourself, simply install Chrome by default on that image, then install the `.crx`. Finally, create an image of that installed state. Voila, your image will contain an installed Chrome with the installed `.crx`.

**Comment by tmowreader** [comment]
But I thought when you install CRX files, it was per profile?  Do you have
a link that says how to do it per install?

**Comment by eladnava** [comment]
Hi @tmowreader,
That's correct, however, if you ship Chrome without any logged in Google profile, and install the extension, it should automatically be applied to the account that the user logs in with in the future.

**Comment by tmowreader** [comment]
So... To clarify... Installing Chrome extensions are on a per Windows
profile basis correct?  If I install the extension into chrome, while
logged into Windows but not logged into Chrome, it is still only good for
that Windows login correct?  If so, that will not work for my situation.

The situation is that I have several mutli use pc's that I'd like to use
this shortcut/app on. Installing it manually is not an option because
several people use each PC.

**Comment by eladnava** [comment]
Hi @tmowreader,
To be honest, I am not sure. I believe that when you install Chrome on Windows you have the option to choose whether to install it for the entire system or just for your current user. I may be wrong as I haven't used Windows in ages.

You are welcome to give it a shot and let me know if it applies per-installation and not per-user.

**Comment by tmowreader** [comment]
Ok thank you. I can try that.

Could I publish this shortcut/app in the Chrome Webstore?  Could I push it
out via GPO then?

**Comment by eladnava** [comment]
Hi @tmowreader,
Unfortunately I am not familiar with Group Policies on Windows to be able to answer that.

As per publishing it, I believe you cannot, as Chrome Web Store has fully deprecated Chrome Apps from being published, except for Chrome OS.
