### ISSUE TITLE
Package is invalid

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [eladnava/applicationize#85]
On my chromebook, I am getting an error after downloading the .crx file, and i can't install it, it gives the error again.
![image](https://user-images.githubusercontent.com/40149778/54654333-12e5e580-4a7b-11e9-9707-48bb7ba3793a.png)

**Comment by eladnava** [comment]
Hi @ShaunTheQuietGamer,
I'd be glad to help investigate.

1) Which website are you trying to Applicationize? Reddit.com? What's the exact URL you put in?

2) How big is that image (reddit_icon.png)?

3) What version of Chrome and OS are you using?

**Comment by ShaunTheQuietGamer** [comment]
Which website are you trying to Applicationize? Reddit.com? What's the exact URL you put in?
Reddit.com

How big is that image (reddit_icon.png)?
24 KB

What version of Chrome and OS are you using?
ChromeOS v74.0.3729.0

**Comment by ShaunTheQuietGamer** [comment]
Also tried without icon. and with https://discordapp.com/app.

**Comment by eladnava** [comment]
Hi @ShaunTheQuietGamer,
Seems your `.crx` file is getting corrupt after download. Possibly try disabling your antivirus momentarily and try again?

Also if you could upload the `.crx` file you are trying to install, that would be great. 👍

**Comment by ShaunTheQuietGamer** [comment]
I am on a Chromebook, there is no antivirus, it might be my adblocker, I will try that. And it deletes the file when I download it, because it gives that error.

**Comment by ShaunTheQuietGamer** [comment]
ok, so it looks like it deletes it, then i reopen the file manager, it shows up again. and i can't upload a .crx to github. i think this might work -- https://drive.google.com/file/d/1_AXNqFHUnqDDDjFGys2UuEicT1QalvIL/view?usp=sharing --

**Comment by ShaunTheQuietGamer** [comment]
(Disabling adblocker didn't help)

**Comment by jedfonner** [comment]
I'm having similar issues.  If I rename the generated .crx to .zip, I can see the contents but when I try to extract, OSX tells me the files are corrupted.  

If I try to do `unzip -l` on the generated crx file, it says "warning: 566 extra bytes at beginning or within zipfile"

**Comment by royandika** [comment]
Same issue here, i've tried http://www.messenger.com but failed. My chrome version: 73.0.3683.86 running on Windows 10 64bit. Antivirus is disabled.
![1](https://user-images.githubusercontent.com/7483898/55055171-c874f200-5094-11e9-8c7c-b9f4cfa208c0.JPG)

**Comment by eladnava** [comment]
Ouch! Looks like the update to Chrome version `73.0.3683.86 (Official Build) (64-bit)` broke Applicationize due to requiring `CRXv3` extension packaging format.

Fixed in https://github.com/eladnava/applicationize/commit/2702b9ebc0a1f12e9261c22416b059d87d8594d8 and deployed to applicationize.me/now thanks to @ahwayakchih.
