### ISSUE TITLE
Top bar is always white.

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [eladnava/applicationize#86]
the top bar isn't showing as the color i set(orange), it is always white. 

ChromeOS V 74.0.3729.38 (Official Build) beta (64-bit)

![Screenshot 2019-04-03 at 6 35 39 PM](https://user-images.githubusercontent.com/40149778/55523908-f2ec1f80-563f-11e9-8037-a955f0f81f21.png)
![Screenshot 2019-04-03 at 6 36 39 PM](https://user-images.githubusercontent.com/40149778/55523913-f7183d00-563f-11e9-9484-77dc149fbcfc.png)

**Comment by eladnava** [comment]
Hi @ShaunTheQuietGamer,
Thanks for the report! I believe I have fixed this in https://github.com/eladnava/applicationize/commit/48e32cd1556dc4a328a03206d3d532ac0a84b8f3.

Please try again now:
https://applicationize.me/now

**Comment by ShaunTheQuietGamer** [comment]
Yup! it is fixed! Thanks!
