### ISSUE TITLE
Can't install on Chromebook

### ISSUE THREAD

**Issue by skulkingfox** [eladnava/applicationize#91]
I just got a Chromebook and am trying to use Applicationize. I can download the .crx file, but when I try to install it from the extensions page by dragging, Chrome just tries to download the file again. 

Am I missing something or did Chrome OS disable being able to drag to install .crx files? Is there a workaround? 

![Screenshot 2019-06-06 at 10 11 13 - Display 2](https://user-images.githubusercontent.com/8932534/59052227-75ad7880-8843-11e9-98d2-a635fc94d322.png)

**Comment by eladnava** [comment]
Hi @skulkingfox,
Please toggle **Developer Mode** in the top right corner and try again. 👍
