### ISSUE TITLE
Install fails with 'crx required proof missing'

### ISSUE THREAD

**Issue by realjax** [eladnava/applicationize#92]
On Windows 10. Chrome 75

**Comment by eladnava** [comment]
Thanks for reporting @realjax!

I opened an upstream issue and awaiting resolution:
https://github.com/oncletom/crx/issues/109

Related: #90

**Comment by eladnava** [comment]
Resolved via https://github.com/eladnava/applicationize/commit/253aead795cad7b256f229e0018f8e258e3f7ee4 (workaround).

Please try again:
https://applicationize.me/now

**Comment by russgalloway** [comment]
![image](https://user-images.githubusercontent.com/627381/60681495-139d5e80-9e55-11e9-87a5-870be287c0be.png)

Just tried using Applicationize.me for YouTube — Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'.  FWIW, same result in dev mode.

macOS 10.14.5, Chrome 75.0.3770.100 — let me know if there's any other useful info I can provide.

**Comment by eladnava** [comment]
Hi @russgalloway,
I just reproduced, and I have a funny solution.

When you toggle Developer Mode on and drag the `.crx` to install it, indeed I got the same error `CRX_REQUIRED_PROOF_MISSING`.

However, if you close and re-open the Extensions page after toggling Developer Mode to on, and then try to install the extension, it will work! 🎉
