### ISSUE TITLE
Extension failed to install in Chrome forked browser

### ISSUE THREAD

**Issue by cmanhoff** [eladnava/applicationize#93]
I am trying to install the extension for Asana in Brave, a fork of Chrome that protects privacy by forcing https connections and squashing third-party cookies and fingerprinting.  Other than that, it's identical to Chrome and I've never had an issue installing extensions.  When I try to install this extension, I get the following error message:

Package is invalid: CRX_REQUIRED_PROOF_MISSING.

![image](https://user-images.githubusercontent.com/22268776/60024000-f1d9f580-9664-11e9-85d2-1a960dcf201e.png)

**Comment by eladnava** [comment]
Hi @cmanhoff,
Can you please try toggling **Developer Mode** in the top right corner of the Extensions page and try dragging and dropping the `.crx` file again?

![Screen Shot 2019-06-26 at 1 37 37 PM](https://user-images.githubusercontent.com/4394189/60144716-9439da80-9817-11e9-8b44-008e1364e981.png)

**Comment by mtudor** [comment]
We have seen this in our environment.  Two machines installed the CRX correctly, one with developer mode on, one with developer mode off.  One machine did not install with developer mode on or off, giving the CRX_REQUIRED_PROOF_MISSING message.  Chrome versions are the same.

I notice that you committed a potential fix - is this applicationize site running this version yet?

**Comment by eladnava** [comment]
Hi @mtudor,
The fix is indeed live. Are you getting this error when **downloading** or when **dragging and dropping** the `.crx` file, and which OS are you running?

**Comment by cmanhoff** [comment]
Hi, the extension did install with the developer mode on.  Thanks.
