### ISSUE TITLE
Extension inside Applicationize?

### ISSUE THREAD

**Issue by EvilistMonkey** [eladnava/applicationize#95]
I'm trying to use applicationize with todoist.com, but I'd like to use 'todoist shortcuts' chrome extension inside of it. Is this possible?

**Comment by eladnava** [comment]
@EvilistMonkey Applicationize doesn't support embedding other Chrome extensions. 

Please read this as a workaround:
https://github.com/eladnava/applicationize/issues/94#issuecomment-513307934
