### ISSUE TITLE
Permissions for camera or mic

### ISSUE THREAD

**Issue by federomano** [eladnava/applicationize#97]
I've been able to use Applicationize perfectly with Microsoft Teams, but when i'm trying to make a video call im unable to give permissions to the tab for accessing my camera and microphone. Ive tried on the extension settings but Chrome says "This extension requires no special permissions". Is there a way to enable this? Thanks!

**Comment by eladnava** [comment]
Hi @federomano,
Sure, please [re-generate your extension](https://applicationize.me/now) and toggle under the `(advanced options)` menu the following option:

Would you like applications to be able to record video via webcam? **YES**
Would you like applications to be able to record audio via microphone? **YES**

**Comment by federomano** [comment]
thanks! and sorry for the miss
