### ISSUE TITLE
Package is invalid: 'CRX_REQUIRED_PROOF_MISSING' in Chrome

### ISSUE THREAD

**Issue by umr55766** [eladnava/applicationize#99]
I am getting `Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'` error when I am trying to open downloaded crx file in my chrome.

I have enabled developer mode in chrome extensions setting page.

So I cloned the repository and ran in local. I have tried using latest crx package version 5.0.1 and also crx3 https://www.npmjs.com/package/crx3 package. Both didn't worked for me. I tweaked this line 
https://github.com/eladnava/applicationize/blob/253aead795cad7b256f229e0018f8e258e3f7ee4/lib/routes/applicationize.js#L18

I am willing to work on fixing this.

Chrome Version 77.0.3865.120
Mac Mojave 10.14.6 (18G103)

**Comment by eladnava** [comment]
Hi @umr55766,
Can you please try now with latest `crx` version `5.0.1` deployed to Applicationize?
https://applicationize.me/now

**Comment by umr55766** [comment]
Now also giving same error @eladnava 😞 
Can we add tests for this project ?

**Comment by umr55766** [comment]
Sorry @eladnava my bad 😭 
I was selecting "Open with : chrome" in download dialog, instead of dragging downloaded extension into extension page.
Just tried dragging into extension page and it worked ! 🎉

**Comment by eladnava** [comment]
Woohoo!

**Comment by tylerburleigh** [comment]
I am experiencing this issue with Chrome version ~80.
I am dragging the file into the extension page.

**Comment by eladnava** [comment]
Hi @tylerburleigh,
I can't reproduce, can you please ensure `Developer Mode` is toggled to `On` in `chrome://extensions/`?

**Comment by tylerburleigh** [comment]
@eladnava tried again today and it worked! I must have made a mistake somewhere along the way

**Comment by eladnava** [comment]
Hi @tylerburleigh,
Great to hear!
